### PR TITLE
Grayscale article buttons

### PR DESCRIPTION
**Pull request by jacogr**
A trial/test/play spawned from this comment - https://github.com/polkadot-js/apps/issues/1044#issuecomment-489099134

Currently only on staking -

Polkadot:Substrate Portal 2019-05-03 15-49-58

### CODE REVIEW

**Comment by Tbaut** [comment]
The problem with grey is that they look disabled.

**Comment by jacogr** [comment]
Agreed, until you hover over the article. Possibly changing the background - def think it needs some playing. (Hence "trial" to get others to take a peek as well)

**Comment by jacogr** [comment]
Adjusted somewhat, the more gray actually looks less disabled imho - but probably more playing required.

Polkadot:Substrate Portal 2019-05-03 18-00-05

**Comment by jacogr** [comment]
Closing, incorporated in #1163

**Pull request closed without merging**
