### PR TITLE
GenericAsset Transfer app

### LINKED ISSUE #1451: New GenericAsset app
New GenericAsset app for [srml-generic-asset module](https://github.com/paritytech/substrate/blob/master/srml/generic-asset)

Similar to transfer one, but add new field for user to set asset id.

Depends on https://github.com/polkadot-js/api/issues/1228

### PR DESCRIPTION
**Pull request by xlc**
Part of #1451
Depends on https://github.com/polkadot-js/api/pull/1229

Needs some more thoughts about the UI/UX. Currently only able to make transfer call.

Can be tested with this branch: https://github.com/cennznet/substrate/tree/node-with-generic-asset

### CODE REVIEW

**Comment by jacogr** [comment]
@xlc The api is current in master now, so the deps should be sorted.

**Comment by xlc** [comment]
Only did a MVP. Later will create a tab to create new token and another one to mint/burn/update permission.

Ideally this should work for a chain without balances module but it requires all the logics about balances module are abstracted which is not easy to implement it cleanly.

**Comment by jacogr** [comment]
Sorry, have not had a gap yet for in-depth. Took a look first thing this morning, and generally the code looks solid (I have some minor nit-picks here and there, but not something that I'll waste effort with).

I just want to give a play-through and got stuck on other things today. So will give my best attempt for tomorrow.

**Comment by jacogr** [comment]
Sorry, seems I introduced conflicts. Was on the way to merging it now that things are more-or-less sane again.

**Comment by jacogr** [comment]
I completely missed the "fix the conflicts" update - this really has hung around for way too long.

So please accept my apologies on this, it certainly was not the intent and nor was it quite a "normal" time. I really appreciate all the work that . has gone into this.

**Pull request merged**
