### PR TITLE
Helper for balance overview

### PR DESCRIPTION
**Pull request by Tbaut**
- closes https://github.com/polkadot-js/apps/issues/1181
- need to refactor the `Unlocking` component (todo).

looks like this, (?) could be toned down a little:
image

### CODE REVIEW

**Comment by jacogr** [comment]
Can't we add it to the label (consistency with what we have everywhere else?) It would also remove the zig-zag on those.

**Comment by Tbaut** [comment]
I tried different one and didn't find it particularly nice:
image

**Comment by jacogr** [comment]
Just needs a bit of padding to the left of the icon. Yes, think it could be a bit much, however that is mostly due to the amount of stuff we have there.

- It aligns visually
- when actually exploring, you can just move the mouse down - so it is faster to get to grips with the actual meaning of all these

**Comment by Tbaut** [comment]
Sounds good, I'll get it back there and see if we can make it a little lighter visually with opacity (apply this generally, I don't think it can hurt too much as long as they are visible)

**Comment by Tbaut** [comment]
image

**Comment by Tbaut** [comment]
closing as pulled by  #1210

**Pull request closed without merging**
