### PR TITLE
Build only apps component via docker

### PR DESCRIPTION
**Pull request by jacogr**

### CODE REVIEW

**Comment by jacogr** [comment]
@philipstanislaus This one should speed up the build by a bit, since it only compiled the actual webpack stuff. (However for a clean build most time is probably spent elsewhere... but every bit helps)

**Comment by philipstanislaus** [comment]
It implies though that you run `yarn build` before `docker build .`, right?

**Comment by jacogr** [comment]
No. The issue is that the yarn build builds all the packages for publishing in addition to the apps component (which is via webpack). 

Effectively it doubles up since the webpack build does all the compilation for the stuff it needs. 

Here it just builds what is needed. (Running yarn clean in root before this will work)

**Comment by philipstanislaus** [comment]
Sounds good!

**Pull request merged**
