### PR TITLE
Add Stakeworld endpoint for kusama

### PR DESCRIPTION
**Pull request by stakeworld**

### CODE REVIEW

**Comment by stakeworld** [comment]
Hi @jacogr, i've had no reaction on this pull request and after reading some of the previous pull request, comments and treasury proposals I suppose it is beter to take smaller steps first, and start with only one dedicted kusama rpc for example. Also, do you have some guidelines available for minimum rpc demands, for example is a full archive node necessary or is a pruned node with for 6 months of history also acceptable? Or maybe other relevant tips?

**Comment by stakeworld** [comment]
Hi @jacogr , I have setup the rpc nodes as archive nodes and also requested some funding, see [treasury request](https://github.com/stakeworld/stakeworld-treasury/blob/master/Q4-RPC-setup-maintenance.md). Let me know if you need additional information or have remarks.

**Comment by jacogr** [comment]
It is really difficult to judge new providers on high-volume environments such as Kusama and Polkadot. I have burned a lot with "unavailability issues" for a number of providers (e.g. more than one) in the past while they sort out their monitoring and infrastructure.

In this case, I'm not terribly excited to have providers SHOUTING over each other in the UI either. (Funnily, I actually do have a check that horribly failed in this case due to not thinking things through, see https://github.com/polkadot-js/apps/blob/0bc1c3a7a61d0827a530b20434fd738034ede57d/packages/apps-config/src/endpoints/index.spec.ts#L114-L116)

So my advice would be -

- prove on something else as a new provider before trying to jump into the deep end (Westend, other paras, etc.) With treasury funding requests (with info around monitoring, availability, infrastructure) I generally can be swayed since the info is there and visible, i.e. I know reasonably well that it won't become more issues logged in my lists saying something like "it doesn't work"

- for my sanity, a different capitalization would help

**Comment by stakeworld** [comment]
Hi @jacogr ,

Thanks for your reply, that helps. I do understand your caution regarding new endpoints, on one side more endpoints help balancing the load, on the other side if they mess up stuff gets unstable and brings work to the maintainers (you) to correct things. 

I have experience with infrastructure and monitoring, i've been running well performing nodes (kusama and polkadot) now for a while and am running a (treasury funded) [snapshot service](https://stakeworld.nl/docs/snapshot) without problems or downtime for a while now. I already have been running [public rpc nodes](https://stakeworld.nl/docs/rpc) for while now to get some experience. Monitoring & alerting has been running for a while and the rpc endpoints are already included in that. Also like I wrote in my [treasury proposal](https://github.com/stakeworld/stakeworld-treasury/blob/master/Q4-RPC-setup-maintenance.md) in case of (hardware) failure I have a backup rpc standing ready, to be honest a pruned one for now but if funding allows I will upgrade that to a full one and also use that for load balancing and more fault tolerance (different providers).

All in all I don't think my experience is less then other providers of endpoints already in the program. 

You are right about the SHOUTING part, when I started I thought that a good idea but maybe it is time to correct that, wil adapt that in the PR. 

On a side note I think it would be nice to have some place for information about the requirements of polkadot.js included rpc node, most logically on the polkadot wiki. For example I see some nodes not having the rpc-methods Safe flag and are very permissive which I think is a risk. It would be nice if the minimum requirements would be described somewhere. I don't mind making wiki pr for this.

What would be your advise to continue? I would prefer to start with one chain, kusama preferably since i'm most active there. I also don't mind firing up a westend rpc node first and include that in the polkadot.js for a starter and include kusama/polkadot later, let me know what you think.

**Comment by stakeworld** [comment]
Hi @jacogr, just to inform you I updated the [treasury request](https://github.com/stakeworld/stakeworld-treasury/blob/master/Q4-RPC-setup-maintenance.md) with some stress testing and metrics and have committed it to "Infrastructure maintenance bounty" for a maintenance funding request. Nodes are running smoothly, adjusted some parameters after the stress tests and will keep monitoring, hopefully you want to give it a go for starting in the polkadot.js app.

**Comment by stakeworld** [comment]
@jacogr FYI I wrote some information about my rpc experiences/setup (securing, proxy server etc) on my [website](https://stakeworld.io/rpc).

**Comment by stakeworld** [comment]
@jacogr, are you still having doubts about this pr? For overview: I got funding from the [treasury](https://docs.google.com/spreadsheets/d/1bdpL37-8YlDKxeWqIKbNmAOz-QCqM0DZJ_LaWbjmDcI) and wrote some setup info on my [website](https://stakeworld.io/docs/rpc) and rewrote the [wiki page](https://wiki.polkadot.network/docs/maintain-wss). Let me know if you have further question, here or on [matrix](https://app.element.io/#/user%2F%40stakeworld%3Amatrix.org)

**Pull request closed without merging**
