### PR TITLE
Add Pop Network to Paseo

### PR DESCRIPTION
**Pull request by al3mart**

### CODE REVIEW

**Comment by al3mart** [comment]
Ready for review!

**Comment by al3mart** [comment]
@TarikGul I have cleaned the commented Pop Network rpcs from Rococo, leaving only the Paseo ones. Also changed the title to reflect these changes.

This is ready to be reviewed! :ok_hand:

**Review by TarikGul — CHANGES_REQUESTED** [review]
Nice, conflicts just need to be resolved

**Comment by al3mart** [comment]
@TarikGul Conflicts solved :ok_hand:

**Comment by TarikGul** [comment]
Now it just needs a `yarn lint`

**Comment by al3mart** [comment]
Alright. CI should be happy now. Thanks for the quick action, Tarik!

**Review by TarikGul — APPROVED** [review]

**Pull request merged**
