### PR TITLE
Scrollable summary bar

### PR DESCRIPTION
**Pull request by rossbulat**
A modified summary bar to span the full width of the page.

* Unified summary bar design while maintaining left | center | right sections when there is space
* No longer hides CardSummary components
* Components viewable / scrollable from any screen width
* Balanced font sizing 
* Decreased box-shadow around the summary bar to let the component sit back slightly from the rest of the page content.

summaryBar

### CODE REVIEW

**Comment by jacogr** [comment]
Humble apologies for not looking at it yet - just been trying to get staking wrangled and more-or-less presentable.

**Comment by rossbulat** [comment]
> Humble apologies for not looking at it yet - just been trying to get staking wrangled and more-or-less presentable.

Not a problem, it's giving me time to iterate further and find that subtlety balance.

**Comment by jacogr** [comment]
Will get to it today

**Comment by rossbulat** [comment]
Note to test: min-height on labelling to equal labels with progress bar height.

**Comment by rossbulat** [comment]
So getting this error after switching to a styled component, not sure where `Key` is coming from.

Screenshot 2019-03-28 at 21 43 43

**Comment by jacogr** [comment]
Marge in latest master - you are behind on your APIs, it is a type the metadata returns.

**Comment by jacogr** [comment]
Ahh, you are not speaking about `Key` - we are missing the PR support in API - https://github.com/paritytech/substrate/commit/044ae4ad0dcc94c858c29cbd24e654c56e28d103

**Comment by jacogr** [comment]
Added a fix to the 0.27 bump in https://github.com/polkadot-js/apps/pull/865

**Comment by jacogr** [comment]
@rossbulat Are you happy atm with this? It looks decent - I am not 100% with the scrolling since it feels a bit wrong since it may or may not be there, but fully willing to give it a go and get it in. All up to you - if you are happy, it goes in.

**Comment by jacogr** [comment]
PS: Nice catch on the PeerInfo.index - I was aware of it, didn't log it, and then it bit us. Thanks for highlighting. (The fix is in master)

**Comment by rossbulat** [comment]
> Are you happy atm with this? It looks decent - I am not 100% with the scrolling since it feels a bit wrong since it may or may not be there, but fully willing to give it a go and get it in. All up to you - if you are happy, it goes in.

Valid point with the scrolling. There will in most cases be an element peeking out of the side that indicates scrolling, but like you say this may not be obvious in all cases. 

I will attempt to integrate some visual indicator signifying there is scrollable content. 

It would be nice to solve all outstanding issues before it being merged - and building upon it. 

> PS. Nice catch 

No problem, excellent turnaround on the fix.

**Comment by rossbulat** [comment]
Think I've found a happy medium for the scrollbar, whereby a light-shaded bar appears when scrolling is active.

The progress bar background has been further lightened to not conflict with the scrollbar.

scrollbar

--
Although not a top concern right now, relies on -webkit scrollbar, perhaps a package like smooth scrollbar could be used for more cross browser compatibility in the future.

**Pull request merged**
