### PR TITLE
Fix SubQuery endpoint for Polkadot

### PR DESCRIPTION
**Pull request by deverka**

### CODE REVIEW

**Review by TarikGul — CHANGES_REQUESTED** [review]
Linter failing. Ordering of keys needs to be adjusted.

**Review by deverka — COMMENTED** [review]
Fixed

**Comment by TarikGul** [comment]
Still needs a `yarn lint`

**Review by deverka — COMMENTED** [review]
Removed space

**Review by TarikGul — APPROVED** [review]

**Pull request merged**
