### PR TITLE
Add Litentry Testnode entry on PolkadotJS

### PR DESCRIPTION
**Pull request by chenzongxiong**
We want to display our testnet entrypoint on the PolkadotJS app

### CODE REVIEW

**Review by jacogr — COMMENTED** [review]
Thank you, couple of comments.

- There are some missing types for this chain, specifically - `Unknown types found, no types for DataSource, QueryKey`
- It doesn't seem to be running or rather stays at block 0?

**Comment by chenzongxiong** [comment]
> * ``
> 
> * It doesn't seem to

It stayed at block 0. We will fix that soon.

**Comment by chenzongxiong** [comment]
> Thank you, couple of comments.
> 
>     * There are some missing types for this chain, specifically - `Unknown types found, no types for DataSource, QueryKey`
> 
>     * It doesn't seem to be running or rather stays at block 0?

It stayed at block 0. We will fix that soon

**Comment by jacogr** [comment]
Not ignoring it. It really just needs the missing types before merging - which is important anyway, as they get added it can align.

**Comment by chenzongxiong** [comment]
>     * running

The testnet is **running**

**Comment by chenzongxiong** [comment]
> Thank you, couple of comments.
> 
>     * There are some missing types for this chain, specifically - `Unknown types found, no types for DataSource, QueryKey`
> 
>     * It doesn't seem to be running or rather stays at block 0?

The testnet is **running**

**Comment by chenzongxiong** [comment]
> Not ignoring it. It really just needs the missing types before merging - which is important anyway, as they get added it can align.

Can you give me some hints, I don't where to fix them. 
Do you have any samples ?

**Comment by jacogr** [comment]
Here are the types as defined by the Litentry team - not sure if they are current - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/litentry.ts

**Comment by jacogr** [comment]
Will merge this, since the above really are only warnings, but it should be kept updated.

**Comment by chenzongxiong** [comment]
> Here are the types as defined by the Litentry team - not sure if they are current - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/litentry.ts

I see. I will remove it since I also copied it from other teams'. 
At this moment, we didn't use it actually. I will update it soon. 

Thanks

**Review by jacogr — APPROVED** [review]

**Pull request merged**
