### PR TITLE
Update moonbeam types bundle 2.0.1

### PR DESCRIPTION
**Pull request by joelamouche**
- update to using our new pre900 type bundle
- update to add ProxyType

### CODE REVIEW

**Comment by joelamouche** [comment]
@jacogr ready for review

**Review by jacogr — CHANGES_REQUESTED** [review]
Please revert the unrelated yarn.lock changes.

**Comment by jacogr** [comment]
Sorry for the delay, going from draft -> PR makes me miss completely miss things in the flood of notification. I skip anything draft when it comes in and then just don't see the status changes, i.e. mentally I just don't look in again.

**Comment by joelamouche** [comment]
@jacogr Ok good to know thanks. When is the next api release scheduled?

**Comment by jacogr** [comment]
It always goes out weekly on Sunday (latest Monday if there are delays or additional testing). The last week was a bit of a change in the normal programming schedule since had to do an early release on Thu.

**Comment by joelamouche** [comment]
Okay PR ready

**Review by jacogr — COMMENTED** [review]
The yarn.lock still contains unrelated changes? (The issue is that none of these have been looked at or tested, so really would prefer it being pin-point with the specific updated dependency instead of everything... Things break with dependency updates)

**Comment by joelamouche** [comment]
closed in favor of https://github.com/polkadot-js/apps/pull/6576/files

**Pull request closed without merging**
