### PR TITLE
Fix broken metadata tab for Paseo

### PR DESCRIPTION
**Pull request by al3mart**
This change removes the oversized background image set for Paseo relay chain. This image would make the metadata tab crash when loading the property `color`.

Closes https://github.com/polkadot-js/apps/issues/10334

This is ready for review @TarikGul.

### CODE REVIEW

**Review by TarikGul — CHANGES_REQUESTED** [review]
Conflicts just need to be reslved but other than that LGTM. Thanks for fixing that.

**Comment by al3mart** [comment]
Conflicts resolved!

**Comment by TarikGul** [comment]
Now it just needs a `yarn lint`

**Comment by al3mart** [comment]
These other lint errors have showed up locally, even though they don't seem related to changes done in this PR I would flag them anyway.


```bash
/home/alemart/Projects/polkadot-js/apps/packages/page-parachains/src/Overview/Parachain.tsx
  95:47  error  Unsafe call of an `any` typed value              @typescript-eslint/no-unsafe-call
  95:83  error  Unsafe member access .isFalse on an `any` value  @typescript-eslint/no-unsafe-member-access

/home/alemart/Projects/polkadot-js/apps/packages/page-parachains/src/Overview/useEvents.ts
  29:11  error  Unsafe assignment of an `any` value                                    @typescript-eslint/no-unsafe-assignment
  31:21  error  Unsafe member access .paraId on an `any` value                         @typescript-eslint/no-unsafe-member-access
  32:11  error  Computed name [descriptor.paraId.toString()] resolves to an any value  @typescript-eslint/no-unsafe-member-access
  32:11  error  Unsafe call of an `any` typed value                                    @typescript-eslint/no-unsafe-call
  32:22  error  Unsafe member access .paraId on an `any` value                         @typescript-eslint/no-unsafe-member-access
  35:9   error  Unsafe assignment of an `any` value                                    @typescript-eslint/no-unsafe-assignment
  35:22  error  Unsafe call of an `any` typed value                                    @typescript-eslint/no-unsafe-call
  35:33  error  Unsafe member access .relayParent on an `any` value                    @typescript-eslint/no-unsafe-member-access

/home/alemart/Projects/polkadot-js/apps/packages/react-components/src/Status/checks.ts
  44:53  error  Unsafe member access .isIncomplete on an `any` value  @typescript-eslint/no-unsafe-member-access
  45:11  error  Unsafe assignment of an `any` value                   @typescript-eslint/no-unsafe-assignment
  45:58  error  Unsafe member access .asIncomplete on an `any` value  @typescript-eslint/no-unsafe-member-access
  47:28  error  Unsafe member access .type on an `any` value          @typescript-eslint/no-unsafe-member-access

```

**Review by TarikGul — APPROVED** [review]
Thank you for the PR! You might have to clear some sort of cache etc for the linting errors. Since there is none in the CI LGTM.

**Pull request merged**
