### PR TITLE
make heiko reachable

### PR DESCRIPTION
**Pull request by GopherJ**
parallel heiko is now reachable: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fheiko-rpc-0.parallel.fi

### CODE REVIEW

**Review by jacogr — APPROVED** [review]

**Comment by jacogr** [comment]
Seems good, failing. Please check CI.

**Comment by GopherJ** [comment]
@jacogr strange it looks ok and I changed only `isUnreachable` which shouldn't warn about sorting, could you give some hints?

**Comment by jacogr** [comment]
`isDisabled` and `isUnreachable` is not being checked for sorting. So this means when enabled again, it may yields issues since it could sit in the wrong place.

**Comment by GopherJ** [comment]
@jacogr kist found that the order is by `text` instead of `info`

**Review by jacogr — APPROVED** [review]

**Pull request merged**
