### PR TITLE
Allow anyone to close a successful council proposal and minor text ch…

### PR DESCRIPTION
**Pull request by lovesh**
…ange.

As per the council pallet, [anyone can close](https://github.com/paritytech/substrate/blob/master/frame/collective/src/lib.rs#L612) a successful council proposal.

Signed-off-by: lovesh <lovesh.bond@gmail.com>

### CODE REVIEW

**Comment by jacogr** [comment]
Thank you, the close part is unlikely to change - the reason for this is that the close operation will swap to the members-only `close_operational` (Substrate PR 7470) as soon as that is ready. (Obviously will fallback to the fully open for older chains).

**Comment by lovesh** [comment]
Hi Jaco.

> close operation will swap to the members-only close_operational

Do you mean `close` will be replaced with `close_operational` in the apps UI?

**Comment by jacogr** [comment]
Yes. The collective close will go through the members-only `close_operational`. With a fallback for older, so the logic will be more of less the following -

```js
tx={api.tx.council.closeOperational || api.tx.council.close}
```

(Same in tech comm)

**Comment by lovesh** [comment]
Thanks.

**Pull request closed without merging**
