### PR TITLE
Add typeBundle for Cere Network

### PR DESCRIPTION
**Pull request by shamilkhan**

### CODE REVIEW

**Review by jacogr — CHANGES_REQUESTED** [review]
This specific file, typesBundle.ts (as per the comment on line 4) is auto-generated, so any merge would just lose the changes completely.

It is built from the config as set in apps-config/api/spec - unless there are changes made there, trying to change the generated file is futile.

**Comment by shamilkhan** [comment]
> This specific file, typesBundle.ts (as per the comment on line 4) is auto-generated, so any merge would just lose the changes completely.
> 
> It is built from the config as set in apps-config/api/spec - unless there are changes made there, trying to change the generated file is futile.

Thanks! Let me fix it.

**Comment by shamilkhan** [comment]
> This specific file, typesBundle.ts (as per the comment on line 4) is auto-generated, so any merge would just lose the changes completely.
> 
> It is built from the config as set in apps-config/api/spec - unless there are changes made there, trying to change the generated file is futile.

Could you check again, please?

**Review by jacogr — APPROVED** [review]
Seems spot-on.

**Pull request merged**
