### PR TITLE
Add max-width to content

### PR DESCRIPTION
**Pull request by MiZiet**
These changes will set a max-width to the app content.

### CODE REVIEW

**Comment by jacogr** [comment]
Not quire convinced, yes.

Existing - 
image

New -
image

The losing of the padding here is non-optimal.

**Comment by krzysztof-jelski** [comment]
Idea -- move the `1750px` and `875px` constants into the theme. What do you think?

**Review by jacogr — APPROVED** [review]
Seems sane :)

Do agree with @krzysztof-jelski that these would be well-suited to extract. (Including using 1750/2, slightly less magic - somebody is going to forget to adjust at some point)

**Comment by jacogr** [comment]
Brilliant, thank you.

**Pull request merged**
