### PR TITLE
MinimumPeriod via consts for 2.x

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/polkadot-js/apps/issues/1410

Would have been nicer with https://github.com/polkadot-js/apps/pull/1416

### CODE REVIEW

**Comment by Stefie** [comment]
My PR should be good to go, but I would appreciate a good look at it since I didn't work with the `ui-api` yet and am therefore not aware of any dependencies in apps that could break down the line

**Comment by jacogr** [comment]
Will adjust now that #1416 is in

**Comment by Stefie** [comment]
Shall I quickly take care of this?

**Comment by jacogr** [comment]
Happy if you take over, not getting to it :) It is just a small change and it sits here in limbo. May as well add it to your other PR as well and close this one.

**Pull request closed without merging**
