### PR TITLE
Remove Dwellir Peaq RPC endpoint

### PR DESCRIPTION
**Pull request by abbaahmad**

### CODE REVIEW

**Comment by TarikGul** [comment]
@jakobilobi Should this be removed?

**Comment by jakobilobi** [comment]
> @jakobilobi Should this be removed?

Yes, it should be removed. The Peaq team asked us to wait with providing a public entry to the network.

**Comment by TarikGul** [comment]
> > @jakobilobi Should this be removed?
> 
> Yes, it should be removed. The Peaq team asked us to wait with providing a public entry to the network.

Okay cool, ping me when this is ready to go in. Thanks for the follow up!

**Comment by jakobilobi** [comment]
> Okay cool, ping me when this is ready to go in. Thanks for the follow up!

This endpoint removal can go in straight away, sorry if that was unclear. We can make a new PR when the endpoint should be available again.

**Pull request merged**
