### PR TITLE
HydraDX -> Hydration rebrand

### PR DESCRIPTION
**Pull request by jak-pan**

### CODE REVIEW

**Comment by jak-pan** [comment]
I have similar question here as in common. Is the key in the map 'hydradx': taken from rpc.chain or something else? Should I add another config with hydration key to support the transition when we change this?

**Review by Cryptopod13 — APPROVED** [review]

**Review by Cryptopod13 — APPROVED** [review]

**Review by Cryptopod13 — APPROVED** [review]

**Review by Cryptopod13 — APPROVED** [review]
1

**Review by Cryptopod13 — COMMENTED** [review]
1

**Review by Cryptopod13 — APPROVED** [review]
1

**Review by Cryptopod13 — APPROVED** [review]
3

**Comment by TarikGul** [comment]
> I have similar question here as in common. Is the key in the map 'hydradx': taken from rpc.chain or something else? Should I add another config with hydration key to support the transition when we change this?

Just answered in Common :)

**Comment by jak-pan** [comment]
Done @TarikGul

**Review by TarikGul — APPROVED** [review]

**Pull request merged**
