### PR TITLE
Added Polkadot RPC endpoint, hosted by Dwellir

### PR DESCRIPTION
**Pull request by Maharacha**
Waiting for proposal.

### CODE REVIEW

**Comment by jacogr** [comment]
Sorry... this is the _completely_ wrong place to ask these things, however since my bots lock old PRs to prevent pesky necro-posting, please forgive me.

I've noticed the Dwellir RPCs for Kusama (unlike other providers) does not run in archive mode, i.e. trying to query old blocks fail since the state is discarded. Is this by design or an oversight?

**Comment by Maharacha** [comment]
> Sorry... this is the _completely_ wrong place to ask these things, however since my bots lock old PRs to prevent pesky necro-posting, please forgive me.
> 
> I've noticed the Dwellir RPCs for Kusama (unlike other providers) does not run in archive mode, i.e. trying to query old blocks fail since the state is discarded. Is this by design or an oversight? (I suppose the question here is probably relevant before this PR does go in)

Our nodes was stuck syncing due to this bug https://github.com/paritytech/polkadot/issues/3778
The get them in sync we had to download a snapshot, which unfortunately is not an archive. A workaround might be to sync the node with an older version (0.9.8) before the bug was introduced, and then upgrade when the node is in sync. We have not tried this though, but can give it a shot if this is a big problem. Otherwise we will wait for the next release where they have fixed the bug.

**Comment by jacogr** [comment]
Ahh, that makes sense. Perfect, really no need to downgrade/upgrade, the next release binary seems to be going out very soon.

**Comment by Maharacha** [comment]
@jacogr Dwellir Polkadot RPC is ready to fly! Feel free to merge.

**Comment by Maharacha** [comment]
> @jacogr Dwellir Polkadot RPC is ready to fly! Feel free to merge.

ping @jacogr

**Review by jacogr — APPROVED** [review]

**Review by jacogr — CHANGES_REQUESTED** [review]
Needs resolving - I disabled one non-operational endpoint earlier.

**Comment by Maharacha** [comment]
> Needs resolving - I disabled one non-operational endpoint earlier.

Rebased now!

**Review by jacogr — APPROVED** [review]

**Pull request merged**
