### PR TITLE
Search/filter functionality of selection dropdowns

### LINKED ISSUE #8194: Allow for search/filter in storage query page
in the storage query page, while selecting the pallet, it would make things a whole lot easier if we could filter the name. 

Screen Shot 2022-10-03 at 12 08 10

E.g. you start typing `st..` in a filed and pallets who's name starts with that should be filtered. Similarly for the name of the storage.

### PR DESCRIPTION
**Pull request by dominikfedor**
added search/filter functionality to selection dropdowns in following pages: 
- Chain state storage and constants
- RPC calls
- Runtime calls
- Extrinsics

I often found myself missing this small feature, and it seems I'm not alone. It enhances usability by allowing users to find pallets and methods more quickly.

Resolves #8194

### CODE REVIEW

**Comment by dominikfedor** [comment]
Hi @jacogr, looking forward to your feedback when convenient. Thanks!

**Comment by devdanco** [comment]
Hi @jacogr is it possible to look at this ? It is great feature. Thank you

**Comment by devdanco** [comment]
hey @TarikGul I really appreciate your time :)

**Comment by TarikGul** [comment]
So far it looks really great, thanks for the addition: Just 2 things:

1. Could you pull in master and push back up so that the CI will run.

2. Could you post a picture of the functionality in the action in the UI.

**Review by TarikGul — CHANGES_REQUESTED** [review]
Looks like `yarn lint` just needs to be run then this will be good to go. Thanks so much!

**Comment by TarikGul** [comment]
Looks like the build is complaining. At first look:

```
Type '(filteredOptions: KeyringSectionOptions, _query: string) => DropdownItemProps[]' is not assignable to type 'boolean | ((options: DropdownItemProps[], value: string) => DropdownItemProps[]) | undefined'.
```

**Review by TarikGul — APPROVED** [review]

**Comment by TarikGul** [comment]
Thanks so much for the contribution.

**Comment by dominikfedor** [comment]
You're welcome, glad to contribute!

**Pull request merged**
