### PR TITLE
Fix Dropdown component

### PR DESCRIPTION
**Pull request by LukeSugiura**
We should eventually convert all components that pass "defaultValue" prop to Dropdown component with "value" prop

### CODE REVIEW

**Comment by LukeSugiura** [comment]
Odd behavior I noticed is that when navigating through accounts options with arrow keys, It focuses section title such as "ACCOUNTS" or "RECENT".

**Comment by LukeSugiura** [comment]
- [ ] remove headers from Dropdown options and use Dropdown.Header component instead.
(https://react.semantic-ui.com/modules/dropdown/#content-header)

**Comment by jacogr** [comment]
When trying to make a transfer -

image

Closed above, opened again via transfer on right side, entered a value - the submit doesn't become active -

image

In the cases where it is used to display values (in this case case block 778476 on Kusama, it does work exactly right (disabled, defaultValue being passed) -

image

**Comment by LukeSugiura** [comment]
The reason why the submit doesn't become active is that initial senderId state on Transfer component remains undefined even after InputAddress component figures out the account address (_defaultValue).

One quick and dirty solution is to call onChange prop right after assigning _defaultValue.
https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/InputAddress/index.tsx#L162

**Comment by jacogr** [comment]
So not sure in this case that it will be only an address thing - for instance in tge Params components where Dropdowns are used for Enums. These are really tricky since the "form creator" really does not know what the full initial value should look like, Having to do so would mean that he needs to understand the full metadata structure populated. So rather, trhis is delegated to the individual components and they (in combination), _always_ fire the initial results - so this all bubbles up and gives the caller the actual initial value.

The components are dual use -

- for "normal" forms, like Transfer where the caller actually knows what he is busy with
- for "metadata" forms, like . the Extrinsic app, where, well, it can be anything as defined by the chain - the elephant is eaten inn small chunks with each component knowing how to treat "structures" of a specific type

So here, just fixing "InputAddress", but breaking other dropdowns, have consequences all-over the UI, especially in the cases where forms are not fixed, but rather dynamically generated from structures, not values.

**Comment by LukeSugiura** [comment]
Thank you for the in-depth explanation!

> for "metadata" forms, like . the Extrinsic app, where, well, it can be anything as defined by the chain - the elephant is eaten inn small chunks with each component knowing how to treat "structures" of a specific type

I honestly wasn't aware of this use case. And now it started to make sense why this bottom-up approach has been deployed.

I should take time to read code around Extrinsic component and play around with democracy app to fully understand the architecture.

**Comment by jacogr** [comment]
You can see the extrinsics app in action just by clicking on the left - as you select the different sections + methods, the details are filled in. (It is far from perfect, struct, especially custom and Vectors are still sort-of usable, but need some TLC)

**Comment by LukeSugiura** [comment]
move to: #1937

**Pull request closed without merging**
