### PR TITLE
New parachain for Kusama

### PR DESCRIPTION
**Pull request by BulatSaif**
New  Bridge hub kusama parachain will be released soon:  https://github.com/paritytech/cumulus/pull/1999

### CODE REVIEW

**Comment by jacogr** [comment]
Are the RPCs active as of yet. (Just asking, if they are not we just need to add an “isUnreachable: true “ flag, otherwise it is ok as-is.

**Comment by BulatSaif** [comment]
Yes, RPC is active but until we don't have the final chainspec the RPC nodes can be down for redeployment. Can we merge this PR after https://github.com/paritytech/cumulus/pull/1999 is merged? (or I can notify here when RPC nodes will have a stable version.)

**Comment by jacogr** [comment]
Will leave this one open until I get an ok.

**Comment by BulatSaif** [comment]
@jacogr , Bridge Hub Kusama should register and onboard tomorrow afternoon/evening.  
The rpc node is up and running. 
We can merge this PR. Thank you

**Review by jacogr — APPROVED** [review]

**Pull request merged**
