### PR TITLE
Reskinning Composable Finance/Picasso Portal Colors

### PR DESCRIPTION
**Pull request by saadjhk**
- [x] Changed Colors for Picasso, Dali and Composable
- [x] Fix logos

### CODE REVIEW

**Comment by RAVIKUMAR96** [comment]
@jacogr can you please review our PR and lets us know if we need to change anything to get it merged

**Comment by RAVIKUMAR96** [comment]
@jacogr can you please review our PR and lets us know if we need to change anything to get it merged. Do we need to resolve "new alerts:1 for Unused variable, import, function or class"  comment only?

**Comment by saadjhk** [comment]
> @jacogr can you please review our PR and lets us know if we need to change anything to get it merged. Do we need to resolve "new alerts:1 for Unused variable, import, function or class" comment only?

@RAVIKUMAR96 i have already resolved the alert raised

**Comment by jacogr** [comment]
Ensure you run `yarn lint` locally - that will auto-fix any issues that CI brings up.

**Comment by saadjhk** [comment]
@jacogr i have run `yarn lint` and it LGTM now

**Review by jacogr — APPROVED** [review]
Thank you!

**Pull request merged**
