### PR TITLE
Rename Statemint* to Asset Hub

### PR DESCRIPTION
**Pull request by BulatSaif**
Follow up for: https://github.com/paritytech/cumulus/pull/2633

Merge after/together when changes from https://github.com/paritytech/cumulus/pull/2633 are released or announced. 

New RPC endpoints are already working.

### CODE REVIEW

**Review by joepetrowski — APPROVED** [review]

**Comment by jacogr** [comment]
When is this meant to go in?

**Comment by joepetrowski** [comment]
AFAIK it could go now, will let @BulatSaif confirm the nodes are up.

**Comment by BulatSaif** [comment]
> AFAIK it could go now, will let @BulatSaif confirm the nodes are up.

Yes, nodes are up and working, @jacogr feel free to merge 

Thank you

**Review by jacogr — APPROVED** [review]
Thank you, really appreciate the effort.

**Pull request merged**
