### PR TITLE
Update Russian translation.

### PR DESCRIPTION
**Pull request by DAle-q**
Full.

### CODE REVIEW

**Comment by jacogr** [comment]
Dupe of #2876 - which we are trying to get in and covers the bulk of the outstanding.

**Comment by DAle-q** [comment]
> Dupe of #2876 - which we are trying to get in and covers the bulk of the outstanding.

Sorry, I don't know how to pull to #2876, you've done a lot of work already, I even didn't see it, I thought the actual translation was on site.

**Comment by Web3Foundation** [comment]
@dale-q apologies for the duplicated work stream and confusion, there was a bit of an overlap for the Russian strings translation work; we’d be glad to have your help for future translation efforts. Please send an email to follow up if you’d like to connect with me and we can discuss the other areas needing help for translation efforts at community@web3.foundation

**Comment by Web3Foundation** [comment]
@jacogr feel free to close now since the other PR was in progress first and this one wasn’t approved / duplicated.

**Comment by jacogr** [comment]
Really do appreciate the effort, however closing to get the existing PR in - in review (still some small issues)

**Pull request closed without merging**
