### PR TITLE
Update Bahasa Indonesia (72%)

### PR DESCRIPTION
**Pull request by nzjourney**

### CODE REVIEW

**Comment by jacogr** [comment]
Thank you! Just merge update master on your side, as it stands it creates conflicts since some changes has already been applied in a previous PR.

**Comment by nzjourney** [comment]
@jacogr ups sorry, i forgot pull from the upstream. now the conflicts are fixed

**Comment by nzjourney** [comment]
@jacogr ups sorry, i forgot pull from the upstream. now the conflicts are fixed, and i add more translation for page-rpc.

**Comment by jacogr** [comment]
Thank you!

**Pull request merged**
