### PR TITLE
Add Centrifuge logo

### PR DESCRIPTION
**Pull request by jacogr**
cc @philipstanislaus

image

### CODE REVIEW

**Comment by philipstanislaus** [comment]
Thanks @jacogr , this is awesome! 

The logo is slightly cut off – could we maybe try with the attached file instead?

Logo_Centrifuge_sw_Logo - C only

**Comment by jacogr** [comment]
Will update.

**Comment by jacogr** [comment]
Zoomed a bit -

image

Looks ok now, will pull that in.

**Comment by philipstanislaus** [comment]
Awesome, thanks! 

This is not reused for telemetry, is it? 

Bildschirmfoto 2020-02-19 um 21 45 06

**Comment by jacogr** [comment]
For Telemetry, the logos are in here - https://github.com/paritytech/substrate-telemetry

(Where exactly, not 100%, it has been a while)

**Comment by philipstanislaus** [comment]
Perfect, found it. Thank you!

**Pull request merged**
