### PR TITLE
 Identicon and error red shading  adjustments for dark theme 

### PR DESCRIPTION
**Pull request by jhonalino**
closest #4294 + a lighter shade and bolded red 

Screen Shot 2021-01-24 at 8 04 08 AM
Screen Shot 2021-01-24 at 8 04 02 AM

### CODE REVIEW

**Comment by jhonalino** [comment]
woot, it passed!

**Comment by jacogr** [comment]
The easiest is always to run `yarn lint` locally - on CI it doesn't actually apply any fixes, locally is does run with `eslint --fix` (Things like type structs may move up/down if the correct overrides are not supplied).

**Review by jacogr — APPROVED** [review]
Brilliant! Thanks an absolute million.

Fo any UI/UX related fixes, not much is logged since there are just tons. So feel free to log and attack anything that you feel can be done better. The focus has mostly been on "keeping up with Substrate/Polkadot" not, really in making the UI rock. Not because it is not really important, there is just x hours in any given day.

**Comment by jhonalino** [comment]
thank you so much for the yarn lint tip! jacogr I appreciate your valuable feedback so much and thank you for reviewing this pr !

**Pull request merged**
