### PR TITLE
Fix & Actualize polkaholic chains

### PR DESCRIPTION
**Pull request by eapo**
1. [Fix polkaholic URL](https://github.com/polkadot-js/apps/commit/f5e30187b2ef885bdc85900b8093b9e48834efdc)
2. 
[Actualize polkaholic chain list](https://github.com/polkadot-js/apps/commit/8b5b50bba95e209acb12d5a05ad40bafb7611d4f)

### CODE REVIEW

**Comment by TarikGul** [comment]
Running the linter should fix the failing tests

**Review by TarikGul — CHANGES_REQUESTED** [review]
Linter

**Comment by TarikGul** [comment]
Linter is still complaining about ordering.

**Comment by eapo** [comment]
I can't understand these Errors.. but it be done
```
/home/runner/work/apps/apps/packages/apps-config/src/links/polkaholic.ts
Error:   38:5  error  Expected object keys to be in ascending order. 'GM' should be before 'Genshiro'          sort-keys
Error:   51:5  error  Expected object keys to be in ascending order. 'KILT Spiritnet' should be before 'Kico'  sort-keys
Error:   79:5  error  Expected object keys to be in ascending order. 'Tanganika' should be before 'subzero'    sort-keys
```

**Comment by sourabhniyogi** [comment]
Disabling Polkaholic support  via #10360 -- we are refactoring into API only solutions since Subscan and polkadot.js serve the userbase adequately

**Review by Cryptopod13 — APPROVED** [review]

**Review by Cryptopod13 — COMMENTED** [review]
kj

**Comment by piggydoughnut** [comment]
Closing as this seems to have been already resolved.

**Pull request closed without merging**
