### PR TITLE
Update Pioneer Blockchain to Metaverse.Network Pioneer 

### PR DESCRIPTION
**Pull request by justinphamnz**
- Bit.Country team updated the blockchain to correct name of Metaverse.Network Tewai and Metaverse.Network Pioneer

### CODE REVIEW

**Review by jacogr — CHANGES_REQUESTED** [review]
Thank you.

CI is failing (tests, see here https://github.com/polkadot-js/apps/actions/runs/6082496456/job/16500405817?pr=9850#step:4:538) since it expects the entries in an alphabetical order. Since the name was changed, this is no longer the case.

Simply move the updated entries down to the correct place and CI will pass, so it can be merged.

**Review by jacogr — CHANGES_REQUESTED** [review]
Sorry to be a pain :)

We are still missing one update, since we changed 2 chains, see https://github.com/polkadot-js/apps/actions/runs/6090821827/job/16526358063?pr=9850#step:4:538

**Comment by justinphamnz** [comment]
> Sorry to be a pain :)
> 
> We are still missing one update, since we changed 2 chains, see https://github.com/polkadot-js/apps/actions/runs/6090821827/job/16526358063?pr=9850#step:4:538

Thanks @jacogr, for reviewing it. All fixed now. 

Appreciate your time.

**Review by jacogr — APPROVED** [review]
Thank you.

**Pull request merged**
