### PR TITLE
Add parachain Lavender by SingNetwork

### PR DESCRIPTION
**Pull request by phamsonha**
- Upload logo singlavender.svg
- Add Lavender config

### CODE REVIEW

**Comment by phamsonha** [comment]
we are now running as test parachain on Rococo testnet 
pls approve this PR 

Screen Shot 2021-09-03 at 21 52 32

**Review by jacogr — COMMENTED** [review]
Just move `rococoSingLavender` alphabetically (based on text, i.e. "Lavender by ...") as per https://github.com/polkadot-js/apps/pull/6067/checks?check_run_id=3522850472#step:3:1191

**Comment by phamsonha** [comment]
> Just move `rococoSingLavender` alphabetically (based on text, i.e. "Lavender by ...") as per https://github.com/polkadot-js/apps/pull/6067/checks?check_run_id=3522850472#step:3:1191

fixed

**Review by jacogr — APPROVED** [review]

**Comment by phamsonha** [comment]
@jacogr everything is ok now, pls verify

**Comment by phamsonha** [comment]
@jacogr pls resolve conflict in packages/apps-config/src/ui/logos/index.ts

**Comment by jacogr** [comment]
One small conflict to resolve from an earlier PR.

**Comment by phamsonha** [comment]
do i need to do anything or you will resolve this conflict?

**Comment by phamsonha** [comment]
@jacogr will you resolve this conflict?

**Comment by jacogr** [comment]
Just merge in master, ensure that both icons are kept.

**Comment by phamsonha** [comment]
> Just merge in master, ensure that both icons are kept.

when will this PR apply to polkadot.js.org/apps?

**Review by jacogr — APPROVED** [review]
Thank you.

**Pull request merged**
