### PR TITLE
Fix electron QR camera permission on mac

### PR DESCRIPTION
**Pull request by wachulski**
Another attempt. This time extending the set of entitlements in use.

### CODE REVIEW

**Comment by wachulski** [comment]
Fixes #4756

**Review by jacogr — APPROVED** [review]
Le's hope for the best.... will make a draft release including this after CI is done.

**Comment by jacogr** [comment]
Building this tag https://github.com/polkadot-js/apps/releases/tag/untagged-ca5c12b0f806cb2ba997 here https://github.com/polkadot-js/apps/actions/runs/939505607

**Comment by wachulski** [comment]
Just downloaded and checked. The app asks for permission and is granted access. Looks promising so far...

**Pull request merged**
