### PR TITLE
support adding discord handle in identity additional field

### PR DESCRIPTION
**Pull request by nbaztec**
**Description**

Allows adding the Discord handle to the IdentityInfo. The value is inserted into the `additional` field.

Discord usage is quite prevalent within the community and many participating parties have a well established discord handles.
This PR will enable them to easily set their verifiable discord entity.

Related https://github.com/paritytech/substrate/pull/12676

### CODE REVIEW

**Comment by crystalin** [comment]
@jacogr Can you get a look at it ? This has been discussed in https://github.com/paritytech/substrate/pull/12676

**Comment by jacogr** [comment]
Can you just please adjust after https://github.com/polkadot-js/apps/pull/8803 has gone in? (Effectively gets rid of the `WrapToggle` parts and passes an actual `Toggle` component via `labelExtra`)

**Comment by nbaztec** [comment]
Updated with https://github.com/polkadot-js/apps/pull/8803

**Comment by crystalin** [comment]
Hi @jacogr do you think this could get merged soon ?

**Comment by crystalin** [comment]
Gentle ping @jacogr :)

**Comment by crystalin** [comment]
Hi @jacogr, 
I don't like to keep pinging people, but not sure what else we can do :(
I believe the PR is ready to be merged

**Review by jacogr — APPROVED** [review]
Does what it says on the tin.

There is a gap through, it is not easily discoverable at all, e.g. for an account that has both twitter & Discord setup, this is what is shown in the sidebar, aka despite being set it is not visible at all via the UI.

Won't block the PR on that, but it is certainly worth an enhancement to show the extra data fields.

image

This is as-set and what it shows when editing again -

image

**Review by jacogr — CHANGES_REQUESTED** [review]
Build & lint seems to be having some issues (not sure why, have not checked the specifics)

**Review by jacogr — APPROVED** [review]
Thank you.

**Comment by crystalin** [comment]
Thank you @jacogr :)

**Pull request merged**
