### PR TITLE
[CD] Deploy dotapps.io(IPFS version) more decentralized with Crust

### PR DESCRIPTION
**Pull request by zikunfan**
## Motivation

Currently polkadot apps is pinned on Pinata's IPFS node, which contains limited IPFS nodes in a centralized way. We would like to contribute and provide a decentralized IPFS pin solution for Polkadot Apps, to further increase the availability and decentralization.

## How we do this

Basically, we use a simple node module called **crust pin**, you can check it's operation principle [here](https://github.com/crustio/crust.js/tree/main/packages/crust-pin#workflow). It will help to **pin our Polkadot Apps onto Crust Maxwell Network which already exceed 1500+ IPFS nodes around the world**. That would definitely improve our application's accessibility in a more distributed way😄.

## What we've done

1. **Uniswap Interface** Github Crust Pin Workflow: https://github.com/crustio/ipfs-crust-pinner/actions/workflows/uniswap-interface.yml
2. **Crust Apps** Github Crust Pin Workflow: https://github.com/crustio/crust-apps/runs/2191965937?check_suite_focus=true

These 2 cases uses the standard Github Action we created:

1. `Crust IPFS Pin`: https://github.com/marketplace/actions/crust-ipfs-pin
2. `Crust IPFS Upload`: https://github.com/marketplace/actions/crust-ipfs-upload

## Additional context

You can contact us at hi@crust.network or @zikun:matrix.org on Element. The pin service will be free for Polkadot, and you can talk to us for the necessary `CRUST_SEEDS` to call Crust IPFS Pin service.

### CODE REVIEW

**Comment by jacogr** [comment]
Will look at the details - but in principle, certainly happy to pin at more places :)

**Comment by zikunfan** [comment]
> Will look at the details - but in principle, certainly happy to pin at more places :)
> 
> It happens weekly, on Mondays with the version bump/deploy.

😄, any question jaco, please feel free to ask me.

**Comment by zikunfan** [comment]
`CRUST_SEEDS` already sent by element

**Comment by jacogr** [comment]
Thank you. Not ignoring this, just traveling tomorrow so has parachain stuff to wrap up. (Just losing tomorrow, nothing more)

will remember to accept the invite and add, that you. Would like to try this out by Monday (release day)

**Review by jacogr — APPROVED** [review]
lgtm, Thank you very much. 

Won't merge today, but the setup is done, so with the SECRET should just work.

Looking forward to it, the more pins the better.

**Comment by zikunfan** [comment]
> lgtm, Thank you very much. 
> 
> 
> 
> Won't merge today, but the setup is done, so with the SECRET should just work.
> 
> 
> 
> Looking forward to it, the more pins the better.

super cool 😎

**Review by jacogr — APPROVED** [review]

**Comment by jacogr** [comment]
Small hiccups - https://github.com/polkadot-js/apps/runs/2218781369?check_suite_focus=true#step:3:925

**Comment by zikunfan** [comment]
> https://github.com/polkadot-js/apps/runs/2218781369?check_suite_focus=true#step:3:925

Cool, it's so happy to see how Crust help Polkadot Apps being more decentralize

**Comment by jacogr** [comment]
The above had some small issue - seems like a new missing? Have not looked at the pin code its of to see why it failed.

**Comment by zikunfan** [comment]
> The above had some small issue - seems like a new missing? Have not looked at the pin code its of to see why it failed.

Fixing, please wait a sec.

**Comment by zikunfan** [comment]
@jacogr please help this pr: https://github.com/polkadot-js/apps/pull/4970

**Pull request merged**
