### PR TITLE
Enable language setting options

### PR DESCRIPTION
**Pull request by LukeSugiura**
This RP enables users to select a language in addition to "auto-detect" option.

Japanese translation for settings page is also added.

### CODE REVIEW

**Comment by LukeSugiura** [comment]
Related PR:
https://github.com/polkadot-js/ui/pull/242

**Comment by jacogr** [comment]
Brilliant! Thank you very much. I'll have a play though on both PRs.

**Comment by jacogr** [comment]
Ok, happy as it stands. However I am not merging it tonight - I will merge in the morning, want to move the language setting drop down options to not pull from UI, but rather from this repo. (Can be in settings itself)

So basically -

- just adjust to still store settings via the UI settings
- but use options generated in apps itself for the language

This will make it much easier for contributors to add more (without dealing with multiple repos)

**Comment by LukeSugiura** [comment]
@jacogr That makes sense for me. Let me know if you need help implementing it.

**Comment by jacogr** [comment]
If you are willing to give it a go, the help would be appreciated - I'm getting to it, my morning turned into being stuck elsewhere, so have not been able to attack it as of yet.

**Comment by jacogr** [comment]
My humble apologies for taking the longest time to get back here - I really try to have a very fast turn-around with any contributions, in this case, well, it was a wish and not a reality.

I really, really appreciate the effort. These PRs that come in out of the blue and solve a real issue with additional functionality, makes my day.

**Comment by LukeSugiura** [comment]
@jacogr No worries! I'm just glad that I could help this project.
I'll create another PR for in-apps language option generation.

**Pull request merged**
