### PR TITLE
Only allow actual accounts to claim

### PR DESCRIPTION
**Pull request by jacogr**
Closes https://github.com/polkadot-js/apps/issues/2829

### CODE REVIEW

**Comment by lsaether** [comment]
Won't this be a problem for people who don't want to expose their accounts to Apps? I'm thinking in the situation of cold storage. Would this still allow for pasting in an address that's not plugged in as an account?

**Comment by jacogr** [comment]
You can't sign with it, so it breaks completely.

**Comment by lsaether** [comment]
That's true for the attestations but the component is also be used for old style Claims using the Ethereum signature (correct me if I'm wrong). So someone could keep their Polkadot keys in cold storage but still use their Eth keys to make the claim. There was at least one person who did it this way during Kusama claims.

**Comment by jacogr** [comment]
Agreed, which is what it was `type='all'` - it should be a check based on type.

**Pull request merged**
