### PR TITLE
[Substrate Files] New files module

### PR DESCRIPTION
**Pull request by badkk**
## Description

***Substrate Files*** is a decentralized storage module which allows substrate-based chains(including `Polkadot/Kusama/Crust/Acala/Clover/Moonbeam/Astar/Phala/...`) users upload their files to [IPFS W3Auth Gateway](https://wiki.crust.network/docs/en/buildIPFSWeb3AuthGW) and decentralized pin their files on [Crust Network](https://crust.network) by using the standard [IPFS W3Auth Pinning Service](https://wiki.crust.network/docs/en/buildIPFSW3AuthPin). This module is a 100% IPFS compatible file storage module, users can pin **NFT files**, host **DApps** or store **on-chain data** in totally DECENTRALIZED way(`guaranteed by Crust protocol`).
Also, the Pinning Service is compatible with several Platforms like `Ethereum`, `Polygon`, `Solana` and `Near`, and funded by [Decentralized Cloud Foundation](https://decloudf.com/). So currently, `Substrate Files` is FREE for all the substrate-based chains!

## Features

Basically, the function is simple, it consist with 2 major parts: `Upload File` and `Manage File Directory`,  **🕹 Live demo is [here](https://gw.crustapps.net/ipfs/QmP6zWegkByr8W1Ujqfv3aLpqvmzKDgU8U5trf2L4hU7ew/#/files)**, you can play it yourself!

### Upload File

- Upload(Single File or Folder)
image

- Choose Gateway
image

- Sign with Polkadot Account
image

- View file info

image

- View file status

> You can copy the cid to [Crust Apps](https://apps.crust.network/?rpc=wss%3A%2F%2Frpc.crust.network#/storage) to see how many IPFS replicas of your file

image

### Manage files directory

Because the whole files module is decentralized, so your file directory is cached in browser, but you can export and import your file directory info.

image

## About this PR

We draft this PR, and just put this module in a separate section, but this can put it anywhere you want.

## References

- [Crust Network](https://crust.network)
- [IPFS Web3 Authentication Gateway](https://wiki.crust.network/docs/en/buildIPFSWeb3AuthGW)
- [IPFS Web3 Authentication Pinning Service](https://wiki.crust.network/docs/en/buildIPFSW3AuthPin)
- [IPFS Public Gateway](https://docs.ipfs.io/concepts/ipfs-gateway/)
- [IPFS Pinning Service](https://docs.ipfs.io/how-to/work-with-pinning-services/#use-an-existing-pinning-service)

### CODE REVIEW

**Review by jacogr — COMMENTED** [review]
Really happy to have this, thanks for the effort. Will dive-through in the next couple of days.

**Comment by badkk** [comment]
> My humble apologies, the last while has been a nightmare with the metadata v14 upgrades - I'll look through in detail in the morning.

It's okay!

**Review by jacogr — CHANGES_REQUESTED** [review]
Thank you. Happy to merge as-is.

I would just request you to merge in the master branch, without that I cannot merge it.

And sorry for the long delay, it has been quite a while since my attention was directed to this repo.

**Comment by badkk** [comment]
> Thank you. Happy to merge as-is.
> 
> I would just request you to merge in the master branch, without that I cannot merge it.
> 
> And sorry for the long delay, it has been quite a while since my attention was directed to this repo.

Already merge with Polkadot latest master!

**Review by jacogr — APPROVED** [review]
Thank you.

**Pull request merged**
