### PR TITLE
Move Zeitgeist Battery Station to Paseo

### PR DESCRIPTION
**Pull request by maltekliemann**
As discussed here: https://github.com/paseo-network/support/issues/93

### CODE REVIEW

**Comment by TarikGul** [comment]
@maltekliemann Is this good to merge?

**Comment by maltekliemann** [comment]
Hey @TarikGul, we're still looking into an issue with the migration. Please hold your horses for now.

**Comment by TarikGul** [comment]
Sounds good, I saw some conversation about it in the issue linked. Feel free to ping me when this is ready!

**Comment by maltekliemann** [comment]
@TarikGul Hey, I think we're good now, ready to merge! Thanks for waiting!

**Pull request merged**
