### PR TITLE
Add OnFinality RPC for Quartz

### PR DESCRIPTION
**Pull request by deverka**

### CODE REVIEW

**Review by jacogr — DISMISSED** [review]
Some small linting issues that should be resolved.

Additionally, we also seem to have a duplicated URL - https://github.com/polkadot-js/apps/actions/runs/4551882157/jobs/8027482094?pr=9245#step:4:546 (from the CI test run)

**Comment by jacogr** [comment]
The endpoint is already used here - https://github.com/polkadot-js/apps/blob/b9fd81a8a2478bb684bfe94ece37fdc0d471ac04/packages/apps-config/src/endpoints/production.ts#L422

**Comment by deverka** [comment]
Thanks and sorry to bother you @jacogr. Should I be adding new endpoints to `production.ts` OR `productionRelayPolkadot.ts` and `productionRelayKusama.ts`

**Comment by jacogr** [comment]
The test conflict here is the following -

- `production` is for stand-alone chains only
- `productionRelayPolkadot ` is for parachains on Polkadot
- `productionRelayKusama` is for parachains on Kusama

A chain cannot be a standalone chain and a parachain and a parachain cannot be connected to 2 networks. So it all depends what type of endpoint it is - and it should appear to where it applies.

**Comment by deverka** [comment]
Thanks, @jacogr, for clarifying it. I removed unnecessary parts.

**Review by jacogr — APPROVED** [review]

**Pull request merged**
