### PR TITLE
Use new colors

### PR DESCRIPTION
**Pull request by Tbaut**
- Fix https://github.com/polkadot-js/apps/issues/245
- Use of the following colors https://coolors.co/4e4e4e-d75ea1-ffffff-96bdc6-98aaae
- For buttons, progress bar, anchors, staking star

image
image

image

image

### CODE REVIEW

**Comment by Tbaut** [comment]
I thought about changing the colors of the lateness progress bar but didn't end up doing it because of the natural human understanding of green, orange, red. The colors should probably be changed for "less loud" ones though.

**Comment by Tbaut** [comment]
- made the anchors a little darker
- toned down the progress bar red, orange, green
- used variables (I used the names from https://coolors.co/ not sure that makes sense..)

selection_161
selection_160selection_159selection_158

**Comment by jacogr** [comment]
Nice!

**Comment by Tbaut** [comment]
Hehe the reason why I chose the name of the colors rather than a descriptive name is because we may want to use the same color for different assets. I'll opt for the go crazy option that solves it then and make the anchor a little darker :)

**Comment by Tbaut** [comment]
BTW I don't have the rights to merge, so feel free to do it :)

**Comment by jacogr** [comment]
Cool. Best is to get it out there and let's see - I think we will obviously need some tweaks, but happy as it stands. So let's see what falls out of the tree when we shake it.

**Pull request merged**
