### PR TITLE
Revert "remove support of karura by elara (#6639)"

### PR DESCRIPTION
**Pull request by UncleTupelo**
This reverts commit b13cb683756fbfe3aff8623503f3bbfc01204129.

### CODE REVIEW

**Comment by jacogr** [comment]
cc @FreePoi - not sure why there is a run-around here?

**Comment by FreePoi** [comment]
> cc @FreePoi - not sure why there is a run-around here?

We decide to remove karura'support by elara. Is there any error in this change?

**Comment by FreePoi** [comment]
Sorry, but is there any error here? [b13cb68](https://github.com/polkadot-js/apps/commit/b13cb683756fbfe3aff8623503f3bbfc01204129) @UncleTupelo

**Comment by jacogr** [comment]
Ok, hence my confusion - I trust @FreePoi since he has the Elara credentials (with a number of PRs as well). Closing this one for wasting my time. feel free to re-open from an Elara account.

**Pull request closed without merging**
