### PR TITLE
Bonded and available as labelExtra in Staking > bond more funds

### LINKED ISSUE #1368: Swap bonder to labelExtra
Pictures -

This one

image

Should look like this one for the extra labels

image

### PR DESCRIPTION
**Pull request by Tbaut**
closes #1368 

this is how it looks, I find it quite hard to read:
image

### CODE REVIEW

**Comment by jacogr** [comment]
Hard to read -

- too much info?
- colors?
- all of the above and more?

**Comment by Tbaut** [comment]
Both the color and the amount of info account for it IMO. Having the length almost match the address also doesn't help since the address is hard to read, but barely needs to be read anyway.
Played a bit, I couldn't get anything better than this (only one balance shown and font 10& less transparent). 
image

**Comment by jacogr** [comment]
Happy with the label color adjustments, it was a bit random. (Just as long as it applied to both the label, the small one and the labelExtra, all good)

**Comment by Tbaut** [comment]
Looks like this now:
image

**Comment by jacogr** [comment]
Well, I like it, CI doesn't. CI seems to win.

**Pull request merged**
