### PR TITLE
Added parser to extract i18n strings

### PR DESCRIPTION
**Pull request by eswarasai**
### Description
- [x] Added extractor for i18n strings
- [x] Categorized i18n strings on a per-app basis
- [x] Loading i18n `locales` from the public folder

Fixes: #1676

### CODE REVIEW

**Comment by eswarasai** [comment]
@jacogr - I've used `i18next-scanner` to extract the i18n strings as it provides custom handlers which we can leverage to replace the strings in the files to include namespaces.

All I need for us is to decide on the namespace separator we're going to use in the codebase. All the packages names are namespaces at the moment. It can be an issue while extracting if we use namespaces like semi-colon or question mark as the strings can contain them. I was wondering to have a bit more structured one's like double hyphen, for example, `app-accounts--Account forgotten`. Let me know your thoughts on this. Thanks!

**Comment by jacogr** [comment]
Yes! This is exactly on the right track. Each app is nicely organized. This is now actually workable since a translator can work through each.

So how does the namespace come into play? Where do these changes need to be made? I would be happy with a `--`, assuming everything is just transparently handled for us.

**Comment by eswarasai** [comment]
@jacogr - Cool, glad to know I'm on the right track. Thanks for pointing me to `withTranslations` usage. I'm trying to leverage that with these namespace translations I've generated. Can probably avoid the namespace separator `--` altogether.

I'll update you here once everything is in place 🙂

**Comment by eswarasai** [comment]
@jacogr - Okay, so I had to move these `locales` into `packages/apps/public` folder for them to load via the `i18n` config via `Backend` module and leverage the `withTranslations` appropriately for each and every package.

While generating these locales, by default, all the keys are being saved in `ui.json` and into their respective `{{namespace}}.json`. Can you please test the `withTranslation` in `translate.ts` by removing the `ui` in the namespace array and see if everything works as expected? Thanks!

**Comment by eswarasai** [comment]
@jacogr - No worries on the review front 😅 

In order for you to test, the locale's being loaded appropriately, you can check the Network tab for `apps.json`, `ui.json` etc. being loaded. By default, it is English language locale that's being fetched.

For supporting other languages, I'm not sure if using `i18next-scanner` we can generate the locale files without removing the value for the existing keys or else, it'll be difficult to actually do the translations.

I'll check both of these and update you first thing tomorrow 🙂

**Comment by eswarasai** [comment]
@jacogr - I've removed the `ui` namespace from being loaded/used across all the packages. While generating the locale files using `i18next-scanner`, the default namespace is `ui` meaning all the i18n strings will be saved by default in `locales/{{lng}}/ui.json`. But this file is never loaded on the UI as I've removed it from the actual `react-i18n` namespaces configuration.

Also, I've tested with generating locale for different languages via the script as well as changing the language programatically using `i18n.changeLanguage()` and can see the locale files of that language being loaded in the Network tab and rendered as well.

PS: Re-running the `yarn i18next-scanner` command after generating the locale files won't update the value of the key in the namespace in case it's changed. These scenarios will be logged onto the console which will be very helpful for debugging purposes.

Let me know if there's anything else needs to be taken care of before merging this one 🙂

**Comment by jacogr** [comment]
@eswarasai This sounds really good. So does this mean that the `ui` namespace is not translated? (i.e. the strings in `react-components`?)

I've actually just cloned when I saw your updated, so starting to play now.

**Comment by eswarasai** [comment]
@jacogr - `react-components` itself is a namespace, so all it's translations are within this. `ui.json` is just a default locale that's being generated by the `i18next-scanner` which can be ignored honestly.

**Comment by jacogr** [comment]
Checking in as well, it works for react-components -

image

**Comment by eswarasai** [comment]
Yep. Each namespace belongs to it's own package name.

**Comment by eswarasai** [comment]
@jacogr - Just merged master and resolved the conflict. Let me know if there's anything else. Thanks!

**Pull request merged**
