### PR TITLE
feat(coretime): add Overview page

### PR DESCRIPTION
**Pull request by bee344**
### Description
Adds the `Overview` page to the `Coretime` tab. This first step aims to add a `Coretime` tab to integrate its functionalities with PJS/APPS, with an `Overview` page that provides some relevant Summary information in a user-friendly manner. 

#### Tasks for Coretime Chain
- [x] Add Summary.
- [x] Add Workload.
- [x] Add Workplan as a separate table.
- [x] Update Workload to improve readability.
- [x] Add filters to Workplan and Workload to filter by core and timeslice.
- [x] Modify appearance.

#### Tasks for Relay Chain
- [x] Add Summary including Spot Traffic, core usage.
- [x] Add Core Descriptors as table.
- [x] Add Core Schedules as table

##### Optional:
- [ ] Modify appearance adding a timeline.

Regarding the appearance, I'm thinking on something simmilar to the `Referenda` page, since the amount of information for Workload and Workplan is substantial.
E.G. Image:

image

This is only as to reference the functionality of collapsing a table and adding a filter.

Part 1 of #10285

### CODE REVIEW

**Comment by bee344** [comment]
A small sidenot: `onDemandCoretimeAssigner` wasn't included in the `Overview` since it isn't in use currently, and although we could make assumptions on how it would look liker, as evidenced with the key for `coreDescriptors`, sometimes stuff doesn't show up as it should. So I think it's better to wait until we have something to work with and then including it.

**Comment by TarikGul** [comment]
After some discussion we decided to switch the logic into 2 pages. 

pages-broker
pages-coretime

**Comment by TarikGul** [comment]
I think the core idea is there but there is some major cosmetic issues we need to fix before we release it:

1. Usage should have a percentage attached to it.  Next index is blank for me as well.
Screenshot 2024-06-10 at 7 16 47 PM

2. The left and right divs here are should have the same vertical width. Also the border of where the 100% task is denoted has no bottom border which is should.
Screenshot 2024-06-10 at 7 17 39 PM

3. When the string increases in task the div should not widen as below.
Screenshot 2024-06-10 at 7 19 04 PM

Currently I am not getting any info in the dropdowns.

**Review by TarikGul — CHANGES_REQUESTED** [review]
Few cosmetic things to change.

**Comment by bee344** [comment]
> 1. Usage should have a percentage attached to it. Next index is blank for me as well.

The info not showing is because of a missmatch between the pallet versions used by Rococo and Westend and the one used by Kusama (v1 vs v0), and that info not appearing in v0. I used Westend and Rococo for testing so I didn't catch that, my bad.

The `usage` percentage on the other hand, when you hover over the graph you can see what's the percentage assigned to that "assignment" (`idle`, `task` or `pool`). Since there can be 3 states at the same time, how do we choose which percentage we show? And if we show all three it gets messy. If you check on Rococo or Westend, you can see the graph has a different color assigned to each "assignment", and hovering over them you can see the percentage of cores dedicated to that "assignment". It's the way I found to have it look cleaner, but let me know if you still think we should change it.

**Comment by TarikGul** [comment]
We also need to ensure we add the `.skip-npm` and `.skip-build` files.

**Comment by piggydoughnut** [comment]
Visual updates :)

## Coretime Chain - Network - Coretime Broker Overview Tab

Screenshot 2024-09-04 at 21 28 11

## Some data 

Screenshot 2024-09-04 at 21 28 37

**Pull request closed without merging**
