### PR TITLE
Added Dwellir RPC endpoint for Centrifuge

### PR DESCRIPTION
**Pull request by Maharacha**

### CODE REVIEW

**Comment by Maharacha** [comment]
Draft until the node is in sync.

**Comment by jacogr** [comment]
SWorry, I reworked the layout of this file to make is (hopefully) less fiddly. It still needs some tweaks, so just a step.

However, this does mean that you would need to re-create this PR on top of that. Sorry about the run around.

**Comment by Maharacha** [comment]
> Sorry, I reworked the layout of this file to make is (hopefully) less fiddly. It still needs some tweaks, so just a step.
> 
> However, this does mean that you would need to re-create this PR on top of that. Sorry about the run around.

No problem! Nice with some refactoring :+1:

**Comment by Maharacha** [comment]
@jacogr rebased, and the node is in sync so this is ready for merge.

**Review by jacogr — APPROVED** [review]

**Pull request merged**
