### PR TITLE
Add SORA-Substrate testnet

### PR DESCRIPTION
**Pull request by stefashkaa**
<h1>Description</h1>

I've added the SORA-Substrate testnet.

### CODE REVIEW

**Comment by stefashkaa** [comment]
Also, I have a question about the icon and color of the header. How to set it correctly?

**Comment by jacogr** [comment]
The color/icon would refer to the node it connects to - so unlike the types, is is not part of the specName.

There are 2 ways -

- https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/colors.ts#L47 - that is based on the name of the chain
- https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/colors.ts#L77 - that is based on the node is connects to, i.e. via the system.name RPC

For the logos, the same applies -

- https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/logos/index.ts#L64 - via system.chain
- https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/ui/logos/index.ts#L84 - via system.name

**Comment by jacogr** [comment]
@stefashkaa seems sane. I'm going to leave it open until you manage to adjust the icon/colors (I also tried to make it more clear in https://github.com/polkadot-js/apps/pull/4060 so it is easier going forward, not perfect, but a start)

**Comment by stefashkaa** [comment]
@jacogr thank you for help with icons and logos. I've fixed it.

**Comment by jacogr** [comment]
Thanks a lot for this, really appreciate it!

**Review by jacogr — APPROVED** [review]

**Pull request merged**
