### PR TITLE
Update translation: Bahasa Indonesia

### PR DESCRIPTION
**Pull request by xryoshi**
This language has not been updated since 4 years ago. so I took the initiative to do an update

### CODE REVIEW

**Comment by piggydoughnut** [comment]
this is amazing! I actually speak a little bit Bahasa 😆  Will review very soon! Thank you.

Did you transalte manually or put it through AI? Just curious.

**Comment by xryoshi** [comment]
@piggydoughnut 70% manually, and 30% using AI, but I'm amazed that the AI results are perfect.

**Review by piggydoughnut — APPROVED** [review]
Great job 🙌🏽  Thank you

**Review by piggydoughnut — CHANGES_REQUESTED** [review]
The translation is great :) I see there are a lot of commits though, however your changes are only in the last two and the rest is from 4 years ago 😅 . Could you please just push the last two commits only so it is nice and clean  🙏🏽  Thank you

**Pull request closed without merging**
