### PR TITLE
Api Bump (DoubleMap)

### LINKED ISSUE #2007: the doublemap value allways return 0 or null
there are my doublemap in substrate:
TokenInfo: double_map T::AccountId, blake2_256(Vec) => Vec<u8>;
TokenInfo: double_map T::AccountId, blake2_256(Vec) => u32;

i update the doublemap's key and value successful. but in https://polkadot.js.org/apps/#/chainstate, my doublemap values can't show correctly, allway 0x00. then i change the value type to u32, it allway return 0.
but on the console, return correct Vec or u32.

tell me what can i do? thanks.

### PR DESCRIPTION
**Pull request by jacogr**
- Pulls in API with DoubleMap hashing adjustments for variable-length params.
- Closes #2007

Slight UI adjustment since consts are now (correctly) without the length, but still working -

image

### CODE REVIEW

**Comment by wjy19990622** [comment]
>     * Pulls in API with DoubleMap hashing adjustments for variable-length params.
> 
>     * Closes #2007
> 
> 
> Slight UI adjustment since consts are now (correctly) without the length, but still working -
> 
> image



>     * Pulls in API with DoubleMap hashing adjustments for variable-length params.
> 
>     * Closes #2007
> 
> 
> Slight UI adjustment since consts are now (correctly) without the length, but still working -
> 
> image

ui
but why my value can't show?

**Comment by wjy19990622** [comment]
> > ```
> > * Pulls in API with DoubleMap hashing adjustments for variable-length params.
> > 
> > * Closes #2007
> > ```
> > 
> > 
> > Slight UI adjustment since consts are now (correctly) without the length, but still working -
> > image
> 
> > ```
> > * Pulls in API with DoubleMap hashing adjustments for variable-length params.
> > 
> > * Closes #2007
> > ```
> > 
> > 
> > Slight UI adjustment since consts are now (correctly) without the length, but still working -
> > image
> 
> ui
> but why my value can't show?

there is my doublwmap:    
TokenInfo: double_map T::AccountId, blake2_256(Vec<u8>) => Vec<u8>;

**Comment by wjy19990622** [comment]
there is my doublwmap:
TokenInfo: double_map T::AccountId, blake2_256(Vec\<u8\>) => Vec\<u8\>;

**Comment by jacogr** [comment]
Check that you polkadot-js/apps version matches -

image

There was def. an issue where `Vec` was incorrectly encoded without the length. The screenshot in the PR is actually with a DoubleMap as per a Substrate 2.x based chain.

**Comment by wjy19990622** [comment]
> Check that you polkadot-js/apps version matches -
> 
> image
> 
> There was def. an issue where `Vec` was incorrectly encoded without the length. The screenshot in the PR is actually with a DoubleMap as per a Substrate 2.x based chain.

i change the code into "TokenInfo: double_map hasher(twox_64_concat) T::AccountId, blake2_256(Vec<u8>) => Vec<u8>;",   it show correctly.

**Pull request merged**
